### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by MedTechCD** [IanPeake/FatMaxxer#1]
Sound notifications are awkward. Keeps repeating the same words 4-5 times before the actual numbers come through. Maybe because I have the calculation update on 5sec?
Notifications on Garmin Edge 830 come through but take up a lot of screen space, see attached screenshot. Even with longer calculation period, the notification stays quite long , hiding the lower half off the screen. Only the first line would be enough, but I don't know if you can decide what comes through.
![Edge830](https://user-images.githubusercontent.com/85841362/121815722-14151580-cc78-11eb-907e-7a49293b7f11.jpg)
Great to see someone is developping an app for real-time alfa1!

**Comment by IanPeake** [comment]
I saw the sound repeat bug a day or two ago and it was definitely released.
But it should be fixed in the most recent version; can you verify?

I will have to support customized notifications---some people have generic
wearables with a lot of screen real estate and want all the info in the
notifications, whereas others like ourselves just need alpha1 and artifacts.

For now it will be something like "Disable notification content" so that
only the title has content.

IanP

**Comment by MedTechCD** [comment]
Regarding audio notifications, I probably missed an update. Just updated now and they work fine. The option of disabling notification text body is better, but it still takes about 1/3th of the screen because of the blank line.
You probably thought about this, but just in case you didn't:
Would it be possible to make the app act like some BLE sensor that can be read by the bike computer and displayed as a selectable field? It would then also be saved in the FIT file.

**Comment by IanPeake** [comment]
Thanks for the feedback. I hadn't thought to try to emulate a BLE sensor---great idea! Would you mind creating new issues for the notification text body blank line and the BLE sensor emulation?

**Comment by MedTechCD** [comment]
Audio notifications are done.
New issue opened for text notifications
