### ISSUE TITLE
Experimental ECG feature ties up a second channel

### ISSUE THREAD

**Issue by IanPeake** [IanPeake/FatMaxxer#22]
The ECG feature may be tying up the second H10 BLE channel.

**Comment by MedTechCD** [comment]
That might explain why I had an empty ecg file.
Last saturday I had an indoor ride where my Polar H10 is paired to

- Garmin Edge 830 in BLE mode (recording HRV for post-ride analysis)
- Trainerday indoor workout app on my phone in BLE mode
- Fatmaxxer on same phone BLE mode

I had to start Fatmaxxer first on my phone or there was no RR stream. Once Fatmaxxer started, Trainerday app was able to connect to the Polar and both apps seemed to do OK. There were a couple artefacts detected (9 in a 90min workout) but the resulting ecg file was empty.
If Trainerday was started first, Fatmaxxer could not connect to the Polar. 
From what I understood, a channel is limited to one device but can be used by multiple apps on that device. But if both channels are needed when using the ecg strip, only the phone could connect to Polar in BLE mode.
Garmin might use the Polar in ANT+, but since there was a post describing more missed beats in ANT+ mode, I disabled ANT+ completely on the Polar.
Will need to do more testing to fully understand this.

**Comment by IanPeake** [comment]
In fact I haven't reproduced this yet. I was diagnosing the issue for an internal tester and it turned out they had just replaced the battery. Replacing the battery causes the H10 to revert to single channel mode until reconfigured with Polar Beat/Flow.

So check you haven't reverted to single channel mode before doing anything elose.

**Comment by MedTechCD** [comment]
Did another test yesterday. 3 segments with artefacts detected were saved in the ecg.csv. Exact same situation as above. If Fatmaxxer is started first, all apps can connect to the Polar. Version 210706_2152.main.5e57fee.
So this seems to be working ok when Fatmaxxer is started first.
